windows:
  mainwindow:
    kwargs:
      confirm_exit: false

data_plugins:
  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable
    kwargs:
        columns: TPZDR

data_plugins:
  notifications:
    provider: qtpyvcp.plugins.notifications:Notifications
    kwargs:
      enabled: True # True | False
      mode: dbus # native | dbus